# Values for memgraph-ha chart - Memgraph HA with controller
# All memgraph values are predefined for HA deployment

memgraph:
  image:
    repository: memgraph/memgraph
    tag: ""  # Uses chart appVersion
    pullPolicy: IfNotPresent

  replicaCount: 3

  # Configure for HA deployment
  service:
    enableBolt: true
    boltPort: 7687
    enableWebsocketMonitoring: false
    enableHttpMonitoring: false

  # Persistent storage configuration
  persistentVolumeClaim:
    createStorageClaim: true
    storageClassName: ""  # Use cluster default
    storageSize: 10Gi
    createLogStorage: true
    logStorageSize: 1Gi

  # Memgraph configuration for replication
  memgraphConfig:
  - "--data-directory=/var/lib/memgraph/mg_data"
  - "--also-log-to-stderr=true"
  - "--replication-restore-state-on-startup=true"

  # Resource configuration
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

  # Service account
  serviceAccount:
    create: true
    annotations: {}
    name: ""

  # Container probes
  container:
    terminationGracePeriodSeconds: 1800
    readinessProbe:
      tcpSocket:
        port: 7687
      failureThreshold: 20
      timeoutSeconds: 10
      periodSeconds: 5
    livenessProbe:
      tcpSocket:
        port: 7687
      failureThreshold: 20
      timeoutSeconds: 10
      periodSeconds: 5
    startupProbe:
      tcpSocket:
        port: 7687
      failureThreshold: 1440
      periodSeconds: 5

  # Init container for system configuration
  sysctlInitContainer:
    enabled: true
    maxMapCount: 262144
    image:
      repository: library/busybox
      tag: latest
      pullPolicy: IfNotPresent

# Controller configuration
controller:
  # Image configuration
  image:
    repository: memgraph-controller
    tag: latest
    pullPolicy: IfNotPresent
  
  # Deployment configuration
  replicaCount: 3
  
  # Namespace configuration
  namespace: memgraph
  
  # Service account
  serviceAccount:
    create: true
    name: memgraph-controller
    annotations: {}
  
  # Service configuration
  service:
    type: ClusterIP
    httpPort: 8080
    boltPort: 7687
  
  # Environment variables
  env:
    appName: memgraph
    reconcileInterval: "30s"
    boltPort: "7687"
    httpPort: "8080"
    statefulsetName: memgraph-ha
    
    # Gateway configuration
    gateway:
      enabled: true
      bindAddress: "0.0.0.0:7687"
      maxConnections: 1000
      timeout: "30s"
      bufferSize: 32768
      healthCheckInterval: "30s"
      connectionTimeout: "10s"
      idleTimeout: "5m"
      maxBytesPerConnection: 1073741824
      cleanupInterval: "1m"
      tls:
        enabled: false
        certPath: "/etc/certs/tls.crt"
        keyPath: "/etc/certs/tls.key"
      rateLimit:
        enabled: true
        rps: 100
        burst: 200
        window: "1m"
      logging:
        level: "info"
        traceEnabled: false
  
  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
  
  # Resource configuration
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  # Probes configuration
  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  readinessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  
  # Labels and annotations
  labels:
    app: memgraph-controller
    component: controller
  
  annotations: {}