# Values for memgraph-ha chart - Memgraph HA with controller
# All memgraph values are predefined for HA deployment

memgraph:
  image:
    repository: memgraph/memgraph
    tag: ""  # Uses chart appVersion
    pullPolicy: IfNotPresent

  replicaCount: 3

  # Configure for HA deployment
  service:
    enableBolt: true
    boltPort: 7687
    enableWebsocketMonitoring: false
    enableHttpMonitoring: false

  # Persistent storage configuration
  persistentVolumeClaim:
    createStorageClaim: true
    storageClassName: ""  # Use cluster default
    storageSize: 10Gi
    createLogStorage: true
    logStorageSize: 1Gi

  # Memgraph configuration for replication
  memgraphConfig:
  - "--data-directory=/var/lib/memgraph/mg_data"
  - "--log-level=INFO"
  - "--also-log-to-stderr=true"
  - "--replication-restore-state-on-startup=true"
  - "--storage-snapshot-on-exit=false"

  # Resource configuration
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

  # Service account
  serviceAccount:
    create: true
    annotations: {}
    name: ""

  extraEnv:
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name

  # Container probes
  container:
    terminationGracePeriodSeconds: 1800
    readinessProbe:
      exec:
        command: ["/bin/sh", "-c", "echo 'RETURN 0;' | timeout 10s mgconsole --username=\"${MEMGRAPH_USER:-memgraph}\" --password=\"${MEMGRAPH_PASSWORD:-}\" >/dev/null 2>&1"]
      failureThreshold: 3
      timeoutSeconds: 10
      periodSeconds: 30
    livenessProbe:
      exec:
        command: ["/bin/sh", "-c", "echo 'RETURN 0;' | timeout 10s mgconsole --username=\"${MEMGRAPH_USER:-memgraph}\" --password=\"${MEMGRAPH_PASSWORD:-}\" >/dev/null 2>&1"]
      failureThreshold: 20
      timeoutSeconds: 10
      periodSeconds: 30
    startupProbe:
      tcpSocket:
        port: 7687
      failureThreshold: 1440
      periodSeconds: 5

  # Lifecycle hooks for graceful shutdown
  lifecycleHooks:
    preStop:
      exec:
        command:
          - /bin/sh
          - -c
          - |
            # Call controller preStop hook API
            # Which will try to wait for the cluster to be in a stable state
            python3 -c "
            import os
            import requests
            import sys
            import time
            pod_name = os.getenv('POD_NAME')
            timeout = int(os.getenv('PRESTOP_TIMEOUT_SECONDS', '600'))
            username = os.getenv('MEMGRAPH_USER', 'memgraph')
            password = os.getenv('MEMGRAPH_PASSWORD', '')
            url = f'http://memgraph-controller:8080/prestop-hook/{pod_name}'
            for _ in range(3):
              try:
                resp = requests.post(url, timeout=timeout, auth=(username, password))
                if resp.status_code == 200:
                  sys.exit(0)
                else:
                  sys.exit(1)
              except requests.exceptions.Timeout:
                sys.exit(1)
              except Exception:
                time.sleep(3)
                continue
            sys.exit(1)
            "

  # Environment variables for memgraph pods
  env:
    - name: PRESTOP_TIMEOUT_SECONDS
      value: "{{ .Values.controller.env.preStopTimeoutSeconds }}"

  # Init container for system configuration
  sysctlInitContainer:
    enabled: true
    maxMapCount: 262144
    image:
      repository: library/busybox
      tag: latest
      pullPolicy: IfNotPresent

  # Init container to clean WAL files for replicas on restart
  # This prevents divergence issues when replica restarts after failover
  # See DATA_DIVERGENCE_TEST.md for details
  initContainers:
    - name: clean-replica-wal
      image: library/busybox
      imagePullPolicy: IfNotPresent
      command: ['/bin/sh', '-c']
      args:
        - |
          echo "========================================="
          echo "Memgraph Replica WAL Cleanup Init Container"
          echo "========================================="

          REPLICATION_META="/var/lib/memgraph/mg_data/replication"
          WAL_DIR="/var/lib/memgraph/mg_data/wal"

          # Check if this is first startup (no metadata exists)
          if [ ! -d "$REPLICATION_META" ]; then
            echo "First startup detected - no replication metadata exists"
            echo "Skipping WAL cleanup"
            exit 0
          fi

          # Check replication role from metadata
          # grep for "replication_role" in all metadata files
          # Use tail -1 to get the LAST (most recent) role, not the first
          ROLE=$(grep -rao '"replication_role":"[^"]*"' "$REPLICATION_META" 2>/dev/null | tail -1 | sed 's/.*"replication_role":"\([^"]*\)".*/\1/')

          echo "Detected replication role: ${ROLE:-unknown}"

          # Only clean WAL if this pod was a replica
          if [ "$ROLE" = "replica" ]; then
            echo "Pod was REPLICA - checking for WAL files"

            if [ -d "$WAL_DIR" ] && [ -n "$(ls -A $WAL_DIR 2>/dev/null)" ]; then
              echo "WAL files found:"
              ls -lah "$WAL_DIR"

              echo "Removing WAL files to prevent divergence..."
              rm -f "$WAL_DIR"/*

              echo "WAL cleanup completed successfully"
              ls -lah "$WAL_DIR"
            else
              echo "No WAL files to clean"
            fi
          else
            echo "Pod was MAIN or unknown role - skipping WAL cleanup"
          fi

          echo "========================================="
          echo "Init container finished"
          echo "========================================="
      volumeMounts:
        - name: memgraph-ha-lib-storage
          mountPath: /var/lib/memgraph
      securityContext:
        runAsUser: 101   # memgraph user
        runAsGroup: 103  # memgraph group

# Controller configuration
controller:
  # Image configuration
  image:
    repository: memgraph-controller
    tag: latest
    pullPolicy: IfNotPresent
  
  # Deployment configuration
  replicaCount: 2
  
  # Namespace configuration
  namespace: memgraph
  
  # Service account
  serviceAccount:
    create: true
    name: memgraph-controller
    annotations: {}
  
  # Service configuration
  service:
    type: ClusterIP
    httpPort: 8080
    boltPort: 7687
  
  # Environment variables
  env:
    appName: memgraph
    reconcileInterval: "30s"
    preStopTimeoutSeconds: "600"
    boltPort: "7687"
    httpPort: "8080"
    statefulsetName: memgraph-ha
    
    # Gateway configuration
    gateway:
      enabled: true
      bindAddress: "0.0.0.0:7687"
      maxConnections: 1000
      timeout: "30s"
      bufferSize: 32768
      healthCheckInterval: "30s"
      connectionTimeout: "10s"
      idleTimeout: "5m"
      maxBytesPerConnection: 1073741824
      cleanupInterval: "1m"
      tls:
        enabled: false
        certPath: "/etc/certs/tls.crt"
        keyPath: "/etc/certs/tls.key"
      rateLimit:
        enabled: true
        rps: 100
        burst: 200
        window: "1m"

    # Read Gateway configuration (disabled by default)
    enableReadGateway: false

    # Admin API configuration (for preStop hooks and debugging)
    enableAdminAPI: true

    logging:
      level: "debug"
      addSource: false
      format: "text"
  
  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
  
  # Resource configuration
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  # Probes configuration
  livenessProbe:
    httpGet:
      path: /livez
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  
  # Labels and annotations
  labels:
    app: memgraph-controller
    component: controller
  
  annotations: {}
