apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: memgraph-cluster

# Build configuration for the controller and test client
build:
  artifacts:
  - image: memgraph-controller
    context: .
    docker:
      dockerfile: Dockerfile
  - image: neo4j-client
    context: tests/client
    docker:
      dockerfile: Dockerfile

# Default deploy configuration (memgraph + controller + test client)
deploy:
  statusCheck: false
  helm:
    releases:
    - name: memgraph-ha
      chartPath: charts/memgraph-ha
      namespace: memgraph
      createNamespace: true
      wait: false
    - name: test-client
      chartPath: tests/client/charts/test-client
      namespace: memgraph
      createNamespace: false
      wait: false
      setValues:
        neo4j.uri: "bolt://memgraph-controller:7687"
        writeInterval: "1000"
  logs:
    prefix: podAndContainer

# Profiles for different deployment scenarios
profiles:

# Profile for E2E testing - builds test image and deploys test job
- name: e2e-test
  build:
    artifacts:
    - image: e2e-test
      context: tests
      docker:
        dockerfile: Dockerfile
  manifests:
    rawYaml:
    - "tests/k8s/serviceaccount.yaml"
    - "tests/k8s/e2e-test-job.yaml"
  deploy:
    statusCheck: false
    kubectl:
      hooks:
        before:
        - host:
            command: ["sh", "-c", "kubectl delete -n memgraph job e2e-test --ignore-not-found"]
        after:
        - host:
            command: ["sh", "-c", "kubectl wait -n memgraph --for=condition=ready pod --selector=job-name=e2e-test --timeout=1m && kubectl logs -n memgraph -f job/e2e-test"]
    # Override default helm to not deploy anything
    helm:
      releases: []
    logs:
      prefix: none
