apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: memgraph-cluster

# Build configuration for the controller and test client
build:
  local:
    useBuildkit: true
  artifacts:
  - image: memgraph-controller
    context: .
    docker:
      dockerfile: Dockerfile
  - image: test-client
    context: tests/client
    docker:
      dockerfile: Dockerfile

# Default deploy configuration (memgraph + controller + test client)
deploy:
  statusCheck: false
  helm:
    releases:
    - name: memgraph-ha
      chartPath: charts/memgraph-ha
      namespace: memgraph
      createNamespace: true
      wait: false
      setValues:
        controller.env.enableAdminAPI: "true"
        controller.env.enableReadGateway: "true"
        memgraph.secrets.enabled: "true"
        memgraph.secrets.name: "test-client"
        memgraph.secrets.userKey: "MEMGRAPH_USER"
        memgraph.secrets.passwordKey: "MEMGRAPH_PASSWORD"
    - name: test-client
      chartPath: tests/client/charts/test-client
      namespace: memgraph
      createNamespace: false
      wait: false
      setValues:
        args: ["write", "bolt://memgraph-gateway:7687"]
        secrets.enabled: "true"
    - name: read-client
      chartPath: tests/client/charts/test-client
      namespace: memgraph
      createNamespace: false
      wait: false
      setValues:
        args: ["read", "bolt://memgraph-gateway-read:7687"]
    - name: bad-client
      chartPath: tests/client/charts/test-client
      namespace: memgraph
      createNamespace: false
      wait: false
      setValues:
        args: ["write", "bolt://memgraph-gateway-read:7687"]

  logs:
    prefix: podAndContainer

# Profiles for different deployment scenarios
profiles: []
