apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: memgraph-cluster

# Build configuration for the controller and test client
build:
  artifacts:
  - image: memgraph-controller
    context: .
    docker:
      dockerfile: Dockerfile
  - image: neo4j-client
    context: tests/client
    docker:
      dockerfile: Dockerfile

# Default deploy configuration (memgraph + controller + test client)
deploy:
  statusCheck: false
  helm:
    releases:
    - name: memgraph-ha
      chartPath: charts/memgraph-ha
      namespace: memgraph
      createNamespace: true
      wait: false
    - name: test-client
      chartPath: tests/client/charts/test-client
      namespace: memgraph
      createNamespace: false
      wait: false
      setValues:
        neo4j.uri: "bolt://memgraph-controller:7687"
        writeInterval: "1000"
  logs:
    prefix: podAndContainer

# Profiles for different deployment scenarios
profiles: []
