apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: memgraph-cluster

# Build configuration for the controller
build:
  artifacts:
  - image: memgraph-controller
    context: .
    docker:
      dockerfile: Dockerfile

# Default deploy configuration (memgraph + controller)
deploy:
  helm:
    releases:
    - name: memgraph-ha
      chartPath: charts/memgraph-ha
      namespace: memgraph
      createNamespace: true
      wait: true

# Port forwarding for development (default profile - memgraph + controller)
portForward:
- resourceType: service
  resourceName: memgraph-controller
  namespace: memgraph
  port: 7687
  localPort: 7687
- resourceType: service
  resourceName: memgraph-controller
  namespace: memgraph
  port: 8080
  localPort: 8080

# Profiles for different deployment scenarios
profiles:
# Profile for deploying only Memgraph cluster (no controller, no port forwarding)
- name: memgraph-only
  deploy:
    helm:
      releases:
      - name: memgraph
        chartPath: charts/memgraph
        namespace: memgraph
        createNamespace: true
        wait: true
