apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.controller.serviceAccount.name }}
  namespace: {{ .Values.controller.namespace }}
  labels:
    {{- toYaml .Values.controller.labels | nindent 4 }}
  {{- with .Values.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.controller.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.controller.labels.app }}
    spec:
      serviceAccountName: {{ .Values.controller.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.controller.securityContext | nindent 8 }}
      containers:
      - name: {{ .Values.controller.labels.app }}
        securityContext:
          {{- toYaml .Values.controller.containerSecurityContext | nindent 10 }}
        image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        env:
        - name: APP_NAME
          value: {{ .Values.controller.env.appName | quote }}
        - name: RECONCILE_INTERVAL
          value: {{ .Values.controller.env.reconcileInterval | quote }}
        - name: BOLT_PORT
          value: {{ .Values.controller.env.boltPort | quote }}
        - name: HTTP_PORT
          value: {{ .Values.controller.env.httpPort | quote }}
        - name: STATEFULSET_NAME
          value: {{ .Values.controller.env.statefulsetName | quote }}
        - name: RELEASE_NAME
          value: {{ .Release.Name | quote }}
        - name: PRESTOP_TIMEOUT_SECONDS
          value: {{ .Values.controller.env.preStopTimeoutSeconds | quote }}
        # Leader election environment variables
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # Logger configuration
        - name: LOG_LEVEL
          value: {{ .Values.controller.env.logging.level | quote }}
        - name: LOG_ADD_SOURCE
          value: {{ .Values.controller.env.logging.addSource | quote }}
        - name: LOG_FORMAT
          value: {{ .Values.controller.env.logging.format | quote }}
        # Gateway configuration
        - name: GATEWAY_BIND_ADDRESS
          value: {{ .Values.controller.env.gateway.bindAddress | quote }}
        - name: GATEWAY_MAX_CONNECTIONS
          value: {{ .Values.controller.env.gateway.maxConnections | quote }}
        - name: GATEWAY_TIMEOUT
          value: {{ .Values.controller.env.gateway.timeout | quote }}
        - name: GATEWAY_BUFFER_SIZE
          value: {{ .Values.controller.env.gateway.bufferSize | quote }}
        - name: GATEWAY_HEALTH_CHECK_INTERVAL
          value: {{ .Values.controller.env.gateway.healthCheckInterval | quote }}
        - name: GATEWAY_CONNECTION_TIMEOUT
          value: {{ .Values.controller.env.gateway.connectionTimeout | quote }}
        - name: GATEWAY_IDLE_TIMEOUT
          value: {{ .Values.controller.env.gateway.idleTimeout | quote }}
        - name: GATEWAY_MAX_BYTES_PER_CONNECTION
          value: {{ .Values.controller.env.gateway.maxBytesPerConnection | quote }}
        - name: GATEWAY_CLEANUP_INTERVAL
          value: {{ .Values.controller.env.gateway.cleanupInterval | quote }}
        - name: GATEWAY_TLS_ENABLED
          value: {{ .Values.controller.env.gateway.tls.enabled | quote }}
        - name: GATEWAY_TLS_CERT_PATH
          value: {{ .Values.controller.env.gateway.tls.certPath | quote }}
        - name: GATEWAY_TLS_KEY_PATH
          value: {{ .Values.controller.env.gateway.tls.keyPath | quote }}
        - name: GATEWAY_RATE_LIMIT_ENABLED
          value: {{ .Values.controller.env.gateway.rateLimit.enabled | quote }}
        - name: GATEWAY_RATE_LIMIT_RPS
          value: {{ .Values.controller.env.gateway.rateLimit.rps | quote }}
        - name: GATEWAY_RATE_LIMIT_BURST
          value: {{ .Values.controller.env.gateway.rateLimit.burst | quote }}
        - name: GATEWAY_RATE_LIMIT_WINDOW
          value: {{ .Values.controller.env.gateway.rateLimit.window | quote }}
        # Admin API configuration (for testing/development)
        - name: ENABLE_ADMIN_API
          value: {{ .Values.controller.env.enableAdminAPI | default "false" | quote }}
        # Read gateway configuration
        - name: ENABLE_READ_GATEWAY
          value: {{ .Values.controller.env.enableReadGateway | default "false" | quote }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: gateway
          containerPort: 7687
          protocol: TCP
        - name: gateway-read
          containerPort: 7688
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.controller.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.controller.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.controller.resources | nindent 10 }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
