apiVersion: apps/v1
kind: Deployment
metadata:
  name: memgraph-controller
  namespace: memgraph
  labels:
    app: memgraph-controller
    component: controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: memgraph-controller
  template:
    metadata:
      labels:
        app: memgraph-controller
    spec:
      serviceAccountName: memgraph-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: memgraph-controller
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        image: "memgraph-controller:latest"
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_NAME
          value: "memgraph"
        - name: NAMESPACE
          value: "memgraph"
        - name: RECONCILE_INTERVAL
          value: "30s"
        - name: BOLT_PORT
          value: "7687"
        - name: HTTP_PORT
          value: "8080"
        - name: STATEFULSET_NAME
          value: "memgraph-ha"
        # Leader election environment variables
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # Gateway configuration
        - name: GATEWAY_ENABLED
          value: "true"
        - name: GATEWAY_BIND_ADDRESS
          value: "0.0.0.0:7687"
        - name: GATEWAY_MAX_CONNECTIONS
          value: "1000"
        - name: GATEWAY_TIMEOUT
          value: "30s"
        - name: GATEWAY_BUFFER_SIZE
          value: "32768"
        - name: GATEWAY_HEALTH_CHECK_INTERVAL
          value: "30s"
        - name: GATEWAY_CONNECTION_TIMEOUT
          value: "10s"
        - name: GATEWAY_IDLE_TIMEOUT
          value: "5m"
        - name: GATEWAY_MAX_BYTES_PER_CONNECTION
          value: "1073741824"
        - name: GATEWAY_CLEANUP_INTERVAL
          value: "1m"
        - name: GATEWAY_TLS_ENABLED
          value: "false"
        - name: GATEWAY_TLS_CERT_PATH
          value: "/etc/certs/tls.crt"
        - name: GATEWAY_TLS_KEY_PATH
          value: "/etc/certs/tls.key"
        - name: GATEWAY_RATE_LIMIT_ENABLED
          value: "true"
        - name: GATEWAY_RATE_LIMIT_RPS
          value: "100"
        - name: GATEWAY_RATE_LIMIT_BURST
          value: "200"
        - name: GATEWAY_RATE_LIMIT_WINDOW
          value: "1m"
        - name: GATEWAY_LOG_LEVEL
          value: "info"
        - name: GATEWAY_TRACE_ENABLED
          value: "false"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: gateway
          containerPort: 7687
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
