apiVersion: v1
kind: Secret
metadata:
  name: memgraph-ha
  labels:
    {{- toYaml .Values.controller.labels | nindent 4 }}
  {{- with .Values.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  token: {{ randAlphaNum 32 | b64enc | quote }}
