apiVersion: v1
kind: Service
metadata:
  name: memgraph-controller
  namespace: memgraph
  labels:
    app: memgraph-controller
    component: controller
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  - port: 7687
    targetPort: gateway
    protocol: TCP
    name: bolt
  selector:
    app: memgraph-controller