apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "memgraph-controller.fullname" . }}
  labels:
    {{- include "memgraph-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "memgraph-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "memgraph-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "memgraph-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: APP_NAME
          value: {{ .Values.env.APP_NAME | quote }}
        - name: NAMESPACE
          value: {{ .Values.env.NAMESPACE | quote }}
        - name: RECONCILE_INTERVAL
          value: {{ .Values.env.RECONCILE_INTERVAL | quote }}
        - name: BOLT_PORT
          value: {{ .Values.env.BOLT_PORT | quote }}
        - name: SERVICE_NAME
          value: {{ .Values.env.SERVICE_NAME | quote }}
        - name: HTTP_PORT
          value: {{ .Values.env.HTTP_PORT | quote }}
        ports:
        {{- if .Values.statusApi.enabled }}
        - name: status-api
          containerPort: {{ .Values.statusApi.port }}
          protocol: TCP
        {{- end }}
        {{- if .Values.health.port }}
        - name: health
          containerPort: {{ .Values.health.port }}
          protocol: TCP
        {{- end }}
        {{- if and .Values.metrics.enabled .Values.metrics.port }}
        - name: metrics
          containerPort: {{ .Values.metrics.port }}
          protocol: TCP
        {{- end }}
        {{- if .Values.health.port }}
        livenessProbe:
          httpGet:
            path: {{ .Values.health.path }}
            port: health
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: {{ .Values.health.path }}
            port: health
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}